xtest <- readRDS(file = "testdata/xtest.rds")
ytest <- readRDS(file = "testdata/ytest.rds")
ztest <- readRDS(file = "testdata/ztest.rds")
cv_mean <- readRDS(file = "testdata/cv_mean.rds")
foldid <- readRDS(file = "testdata/foldid.rds")
