fit_model <- function(x,
                      mattype_x,
                      y,
                      external,
                      fixed,
                      weights_user,
                      intercept,
                      standardize,
                      penalty_type,
                      cmult,
                      quantiles,
                      num_penalty,
                      penalty_ratio,
                      user_penalty,
                      user_penalty_ext,
                      lower_cl,
                      upper_cl,
                      family,
                      thresh,
                      maxit,
                      dfmax,
                      pmax) {

    is_sparse_ext <- is(external, "sparseMatrix")

    # pass matrices or ptrs to matrices depending on type
    if (mattype_x %in% c(1, 3)) {
        if (is_sparse_ext)
            fit <- fitModelRcpp(x = x,
                                mattype_x = mattype_x,
                                y = y,
                                ext = external,
                                is_sparse_ext,
                                fixed = fixed,
                                weights_user = weights_user,
                                intr = intercept,
                                stnd = standardize,
                                penalty_type = penalty_type,
                                cmult = cmult,
                                quantiles = quantiles,
                                num_penalty = num_penalty,
                                penalty_ratio = penalty_ratio,
                                penalty_user = user_penalty,
                                penalty_user_ext = user_penalty_ext,
                                lower_cl = lower_cl,
                                upper_cl = upper_cl,
                                family = family,
                                thresh = thresh,
                                maxit = maxit,
                                ne = dfmax,
                                nx = pmax)
        else
            fit <- fitModelRcpp(x = x,
                                mattype_x = mattype_x,
                                y = y,
                                ext = external,
                                is_sparse_ext,
                                fixed = fixed,
                                weights_user = weights_user,
                                intr = intercept,
                                stnd = standardize,
                                penalty_type = penalty_type,
                                cmult = cmult,
                                quantiles = quantiles,
                                num_penalty = num_penalty,
                                penalty_ratio = penalty_ratio,
                                penalty_user = user_penalty,
                                penalty_user_ext = user_penalty_ext,
                                lower_cl = lower_cl,
                                upper_cl = upper_cl,
                                family = family,
                                thresh = thresh,
                                maxit = maxit,
                                ne = dfmax,
                                nx = pmax)
    } else {
        if (is_sparse_ext)
            fit <- fitModelRcpp(x = x@address,
                                mattype_x = mattype_x,
                                y = y,
                                ext = external,
                                is_sparse_ext,
                                fixed = fixed,
                                weights_user = weights_user,
                                intr = intercept,
                                stnd = standardize,
                                penalty_type = penalty_type,
                                cmult = cmult,
                                quantiles = quantiles,
                                num_penalty = num_penalty,
                                penalty_ratio = penalty_ratio,
                                penalty_user = user_penalty,
                                penalty_user_ext = user_penalty_ext,
                                lower_cl = lower_cl,
                                upper_cl = upper_cl,
                                family = family,
                                thresh = thresh,
                                maxit = maxit,
                                ne = dfmax,
                                nx = pmax)
        else
            fit <- fitModelRcpp(x = x@address,
                                mattype_x = mattype_x,
                                y = y,
                                ext = external,
                                is_sparse_ext,
                                fixed = fixed,
                                weights_user = weights_user,
                                intr = intercept,
                                stnd = standardize,
                                penalty_type = penalty_type,
                                cmult = cmult,
                                quantiles = quantiles,
                                num_penalty = num_penalty,
                                penalty_ratio = penalty_ratio,
                                penalty_user = user_penalty,
                                penalty_user_ext = user_penalty_ext,
                                lower_cl = lower_cl,
                                upper_cl = upper_cl,
                                family = family,
                                thresh = thresh,
                                maxit = maxit,
                                ne = dfmax,
                                nx = pmax)
    }
    return(fit)
}
