# Function to prepare Gaussian outcome for model fitting
gaussian <- function(x,
                     y,
                     external,
                     unpen,
                     penalty,
                     weights,
                     isd,
                     intr,
                     is_sparse,
                     control) {

    y <- as.double(drop(y))

    if (is_sparse) {
        fit <- gaussian_fit_sparse(x_ = x,
                                   y_ = y,
                                   ext_ = external,
                                   fixed_ = unpen,
                                   nobs = nrow(x),
                                   nvar = ncol(x),
                                   nvar_ext = ncol(external),
                                   nvar_unpen = ncol(unpen),
                                   w = weights,
                                   ptype = penalty$ptype,
                                   tau = penalty$tau,
                                   tau_ext = penalty$tau_ext,
                                   cmult = penalty$cmult,
                                   lower_cl = control$lower_limits,
                                   upper_cl = control$upper_limits,
                                   ne = control$dfmax,
                                   nx = control$pmax,
                                   nlam = penalty$num_penalty,
                                   nlam_ext = penalty$num_penalty_ext,
                                   pratio = penalty$penalty_ratio,
                                   pratio_ext = penalty$penalty_ratio_ext,
                                   ulam_ = penalty$user_penalty,
                                   ulam_ext_ = penalty$user_penalty_ext,
                                   thr = control$tolerance,
                                   maxit = control$max_iterations,
                                   earlyStop = control$earlyStop,
                                   isd = isd[1],
                                   isd_ext = isd[2],
                                   intr = intr[1],
                                   intr_ext = intr[2])
    } else {
        fit <- gaussian_fit(x_ = x,
                            y_ = y,
                            ext_ = external,
                            fixed_ = unpen,
                            nobs = nrow(x),
                            nvar = ncol(x),
                            nvar_ext = ncol(external),
                            nvar_unpen = ncol(unpen),
                            w = weights,
                            ptype = penalty$ptype,
                            tau = penalty$tau,
                            tau_ext = penalty$tau_ext,
                            cmult = penalty$cmult,
                            lower_cl = control$lower_limits,
                            upper_cl = control$upper_limits,
                            ne = control$dfmax,
                            nx = control$pmax,
                            nlam = penalty$num_penalty,
                            nlam_ext = penalty$num_penalty_ext,
                            pratio = penalty$penalty_ratio,
                            pratio_ext = penalty$penalty_ratio_ext,
                            ulam_ = penalty$user_penalty,
                            ulam_ext_ = penalty$user_penalty_ext,
                            thr = control$tolerance,
                            maxit = control$max_iterations,
                            earlyStop = control$earlyStop,
                            isd = isd[1],
                            isd_ext = isd[2],
                            intr = intr[1],
                            intr_ext = intr[2])
    }
    return(fit)
}
