# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_data <- function(nobs, nvar, nvar_ext, nvar_total, x, ext, w, isd, isd_ext, intr, intr_ext, xm, xv, xs) {
    .Call(`_hierr_create_data`, nobs, nvar, nvar_ext, nvar_total, x, ext, w, isd, isd_ext, intr, intr_ext, xm, xv, xs)
}

standardize_vec <- function(y, w, ym, ys, intr) {
    invisible(.Call(`_hierr_standardize_vec`, y, w, ym, ys, intr))
}

coord_desc <- function(x, resid, w, ptype, no, nvar, nvar_total, cmult, upper_cl, lower_cl, ne, nx, cur_lam, thr, maxit, xv, coef, b, g, rsq, rsq_cur, mm, errcode, nlp, idx_lam) {
    invisible(.Call(`_hierr_coord_desc`, x, resid, w, ptype, no, nvar, nvar_total, cmult, upper_cl, lower_cl, ne, nx, cur_lam, thr, maxit, xv, coef, b, g, rsq, rsq_cur, mm, errcode, nlp, idx_lam))
}

gaussian_fit <- function(ptype, nobs, nvar, nvar_ext, x_, y_, ext_, w, cmult, lower_cl, upper_cl, ne, nx, nlam, nlam_ext, pratio, pratio_ext, ulam_, ulam_ext_, thr, maxit, isd, isd_ext, intr, intr_ext) {
    .Call(`_hierr_gaussian_fit`, ptype, nobs, nvar, nvar_ext, x_, y_, ext_, w, cmult, lower_cl, upper_cl, ne, nx, nlam, nlam_ext, pratio, pratio_ext, ulam_, ulam_ext_, thr, maxit, isd, isd_ext, intr, intr_ext)
}

